// Code generated by MockGen. DO NOT EDIT.
// Source: ./nats_kv.go

// Package nats_kv is a generated GoMock package.
package nats

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	nats "github.com/nats-io/nats.go"
)

// MockNatsJetStreamContextInterface is a mock of NatsJetStreamContextInterface interface.
type MockNatsJetStreamContextInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNatsJetStreamContextInterfaceMockRecorder
}

// MockNatsJetStreamContextInterfaceMockRecorder is the mock recorder for MockNatsJetStreamContextInterface.
type MockNatsJetStreamContextInterfaceMockRecorder struct {
	mock *MockNatsJetStreamContextInterface
}

// NewMockNatsJetStreamContextInterface creates a new mock instance.
func NewMockNatsJetStreamContextInterface(ctrl *gomock.Controller) *MockNatsJetStreamContextInterface {
	mock := &MockNatsJetStreamContextInterface{ctrl: ctrl}
	mock.recorder = &MockNatsJetStreamContextInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNatsJetStreamContextInterface) EXPECT() *MockNatsJetStreamContextInterfaceMockRecorder {
	return m.recorder
}

// AccountInfo mocks base method.
func (m *MockNatsJetStreamContextInterface) AccountInfo(opts ...nats.JSOpt) (*nats.AccountInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AccountInfo", varargs...)
	ret0, _ := ret[0].(*nats.AccountInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountInfo indicates an expected call of AccountInfo.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) AccountInfo(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountInfo", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).AccountInfo), opts...)
}

// AddConsumer mocks base method.
func (m *MockNatsJetStreamContextInterface) AddConsumer(stream string, cfg *nats.ConsumerConfig, opts ...nats.JSOpt) (*nats.ConsumerInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{stream, cfg}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddConsumer", varargs...)
	ret0, _ := ret[0].(*nats.ConsumerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddConsumer indicates an expected call of AddConsumer.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) AddConsumer(stream, cfg interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{stream, cfg}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConsumer", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).AddConsumer), varargs...)
}

// AddStream mocks base method.
func (m *MockNatsJetStreamContextInterface) AddStream(cfg *nats.StreamConfig, opts ...nats.JSOpt) (*nats.StreamInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{cfg}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddStream", varargs...)
	ret0, _ := ret[0].(*nats.StreamInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddStream indicates an expected call of AddStream.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) AddStream(cfg interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{cfg}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStream", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).AddStream), varargs...)
}

// ChanQueueSubscribe mocks base method.
func (m *MockNatsJetStreamContextInterface) ChanQueueSubscribe(subj, queue string, ch chan *nats.Msg, opts ...nats.SubOpt) (*nats.Subscription, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{subj, queue, ch}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ChanQueueSubscribe", varargs...)
	ret0, _ := ret[0].(*nats.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChanQueueSubscribe indicates an expected call of ChanQueueSubscribe.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) ChanQueueSubscribe(subj, queue, ch interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{subj, queue, ch}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChanQueueSubscribe", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).ChanQueueSubscribe), varargs...)
}

// ChanSubscribe mocks base method.
func (m *MockNatsJetStreamContextInterface) ChanSubscribe(subj string, ch chan *nats.Msg, opts ...nats.SubOpt) (*nats.Subscription, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{subj, ch}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ChanSubscribe", varargs...)
	ret0, _ := ret[0].(*nats.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChanSubscribe indicates an expected call of ChanSubscribe.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) ChanSubscribe(subj, ch interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{subj, ch}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChanSubscribe", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).ChanSubscribe), varargs...)
}

// ConsumerInfo mocks base method.
func (m *MockNatsJetStreamContextInterface) ConsumerInfo(stream, name string, opts ...nats.JSOpt) (*nats.ConsumerInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{stream, name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ConsumerInfo", varargs...)
	ret0, _ := ret[0].(*nats.ConsumerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumerInfo indicates an expected call of ConsumerInfo.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) ConsumerInfo(stream, name interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{stream, name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumerInfo", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).ConsumerInfo), varargs...)
}

// ConsumerNames mocks base method.
func (m *MockNatsJetStreamContextInterface) ConsumerNames(stream string, opts ...nats.JSOpt) <-chan string {
	m.ctrl.T.Helper()
	varargs := []interface{}{stream}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ConsumerNames", varargs...)
	ret0, _ := ret[0].(<-chan string)
	return ret0
}

// ConsumerNames indicates an expected call of ConsumerNames.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) ConsumerNames(stream interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{stream}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumerNames", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).ConsumerNames), varargs...)
}

// Consumers mocks base method.
func (m *MockNatsJetStreamContextInterface) Consumers(stream string, opts ...nats.JSOpt) <-chan *nats.ConsumerInfo {
	m.ctrl.T.Helper()
	varargs := []interface{}{stream}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Consumers", varargs...)
	ret0, _ := ret[0].(<-chan *nats.ConsumerInfo)
	return ret0
}

// Consumers indicates an expected call of Consumers.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) Consumers(stream interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{stream}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consumers", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).Consumers), varargs...)
}

// ConsumersInfo mocks base method.
func (m *MockNatsJetStreamContextInterface) ConsumersInfo(stream string, opts ...nats.JSOpt) <-chan *nats.ConsumerInfo {
	m.ctrl.T.Helper()
	varargs := []interface{}{stream}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ConsumersInfo", varargs...)
	ret0, _ := ret[0].(<-chan *nats.ConsumerInfo)
	return ret0
}

// ConsumersInfo indicates an expected call of ConsumersInfo.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) ConsumersInfo(stream interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{stream}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumersInfo", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).ConsumersInfo), varargs...)
}

// CreateKeyValue mocks base method.
func (m *MockNatsJetStreamContextInterface) CreateKeyValue(cfg *nats.KeyValueConfig) (nats.KeyValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKeyValue", cfg)
	ret0, _ := ret[0].(nats.KeyValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKeyValue indicates an expected call of CreateKeyValue.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) CreateKeyValue(cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKeyValue", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).CreateKeyValue), cfg)
}

// CreateObjectStore mocks base method.
func (m *MockNatsJetStreamContextInterface) CreateObjectStore(cfg *nats.ObjectStoreConfig) (nats.ObjectStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateObjectStore", cfg)
	ret0, _ := ret[0].(nats.ObjectStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateObjectStore indicates an expected call of CreateObjectStore.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) CreateObjectStore(cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateObjectStore", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).CreateObjectStore), cfg)
}

// DeleteConsumer mocks base method.
func (m *MockNatsJetStreamContextInterface) DeleteConsumer(stream, consumer string, opts ...nats.JSOpt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{stream, consumer}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteConsumer", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteConsumer indicates an expected call of DeleteConsumer.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) DeleteConsumer(stream, consumer interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{stream, consumer}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConsumer", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).DeleteConsumer), varargs...)
}

// DeleteKeyValue mocks base method.
func (m *MockNatsJetStreamContextInterface) DeleteKeyValue(bucket string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteKeyValue", bucket)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteKeyValue indicates an expected call of DeleteKeyValue.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) DeleteKeyValue(bucket interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteKeyValue", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).DeleteKeyValue), bucket)
}

// DeleteMsg mocks base method.
func (m *MockNatsJetStreamContextInterface) DeleteMsg(name string, seq uint64, opts ...nats.JSOpt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{name, seq}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteMsg", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMsg indicates an expected call of DeleteMsg.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) DeleteMsg(name, seq interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{name, seq}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMsg", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).DeleteMsg), varargs...)
}

// DeleteObjectStore mocks base method.
func (m *MockNatsJetStreamContextInterface) DeleteObjectStore(bucket string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObjectStore", bucket)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObjectStore indicates an expected call of DeleteObjectStore.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) DeleteObjectStore(bucket interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObjectStore", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).DeleteObjectStore), bucket)
}

// DeleteStream mocks base method.
func (m *MockNatsJetStreamContextInterface) DeleteStream(name string, opts ...nats.JSOpt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteStream", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStream indicates an expected call of DeleteStream.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) DeleteStream(name interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStream", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).DeleteStream), varargs...)
}

// GetLastMsg mocks base method.
func (m *MockNatsJetStreamContextInterface) GetLastMsg(name, subject string, opts ...nats.JSOpt) (*nats.RawStreamMsg, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{name, subject}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLastMsg", varargs...)
	ret0, _ := ret[0].(*nats.RawStreamMsg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastMsg indicates an expected call of GetLastMsg.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) GetLastMsg(name, subject interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{name, subject}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastMsg", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).GetLastMsg), varargs...)
}

// GetMsg mocks base method.
func (m *MockNatsJetStreamContextInterface) GetMsg(name string, seq uint64, opts ...nats.JSOpt) (*nats.RawStreamMsg, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{name, seq}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMsg", varargs...)
	ret0, _ := ret[0].(*nats.RawStreamMsg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMsg indicates an expected call of GetMsg.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) GetMsg(name, seq interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{name, seq}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMsg", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).GetMsg), varargs...)
}

// KeyValue mocks base method.
func (m *MockNatsJetStreamContextInterface) KeyValue(bucket string) (nats.KeyValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeyValue", bucket)
	ret0, _ := ret[0].(nats.KeyValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// KeyValue indicates an expected call of KeyValue.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) KeyValue(bucket interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeyValue", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).KeyValue), bucket)
}

// KeyValueStoreNames mocks base method.
func (m *MockNatsJetStreamContextInterface) KeyValueStoreNames() <-chan string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeyValueStoreNames")
	ret0, _ := ret[0].(<-chan string)
	return ret0
}

// KeyValueStoreNames indicates an expected call of KeyValueStoreNames.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) KeyValueStoreNames() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeyValueStoreNames", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).KeyValueStoreNames))
}

// KeyValueStores mocks base method.
func (m *MockNatsJetStreamContextInterface) KeyValueStores() <-chan nats.KeyValueStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "KeyValueStores")
	ret0, _ := ret[0].(<-chan nats.KeyValueStatus)
	return ret0
}

// KeyValueStores indicates an expected call of KeyValueStores.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) KeyValueStores() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "KeyValueStores", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).KeyValueStores))
}

// ObjectStore mocks base method.
func (m *MockNatsJetStreamContextInterface) ObjectStore(bucket string) (nats.ObjectStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ObjectStore", bucket)
	ret0, _ := ret[0].(nats.ObjectStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ObjectStore indicates an expected call of ObjectStore.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) ObjectStore(bucket interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObjectStore", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).ObjectStore), bucket)
}

// ObjectStoreNames mocks base method.
func (m *MockNatsJetStreamContextInterface) ObjectStoreNames(opts ...nats.ObjectOpt) <-chan string {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ObjectStoreNames", varargs...)
	ret0, _ := ret[0].(<-chan string)
	return ret0
}

// ObjectStoreNames indicates an expected call of ObjectStoreNames.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) ObjectStoreNames(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObjectStoreNames", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).ObjectStoreNames), opts...)
}

// ObjectStores mocks base method.
func (m *MockNatsJetStreamContextInterface) ObjectStores(opts ...nats.ObjectOpt) <-chan nats.ObjectStoreStatus {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ObjectStores", varargs...)
	ret0, _ := ret[0].(<-chan nats.ObjectStoreStatus)
	return ret0
}

// ObjectStores indicates an expected call of ObjectStores.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) ObjectStores(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObjectStores", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).ObjectStores), opts...)
}

// Publish mocks base method.
func (m *MockNatsJetStreamContextInterface) Publish(subj string, data []byte, opts ...nats.PubOpt) (*nats.PubAck, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{subj, data}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Publish", varargs...)
	ret0, _ := ret[0].(*nats.PubAck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) Publish(subj, data interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{subj, data}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).Publish), varargs...)
}

// PublishAsync mocks base method.
func (m *MockNatsJetStreamContextInterface) PublishAsync(subj string, data []byte, opts ...nats.PubOpt) (nats.PubAckFuture, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{subj, data}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PublishAsync", varargs...)
	ret0, _ := ret[0].(nats.PubAckFuture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishAsync indicates an expected call of PublishAsync.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) PublishAsync(subj, data interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{subj, data}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAsync", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).PublishAsync), varargs...)
}

// PublishAsyncComplete mocks base method.
func (m *MockNatsJetStreamContextInterface) PublishAsyncComplete() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishAsyncComplete")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// PublishAsyncComplete indicates an expected call of PublishAsyncComplete.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) PublishAsyncComplete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAsyncComplete", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).PublishAsyncComplete))
}

// PublishAsyncPending mocks base method.
func (m *MockNatsJetStreamContextInterface) PublishAsyncPending() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishAsyncPending")
	ret0, _ := ret[0].(int)
	return ret0
}

// PublishAsyncPending indicates an expected call of PublishAsyncPending.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) PublishAsyncPending() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAsyncPending", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).PublishAsyncPending))
}

// PublishMsg mocks base method.
func (m_2 *MockNatsJetStreamContextInterface) PublishMsg(m *nats.Msg, opts ...nats.PubOpt) (*nats.PubAck, error) {
	m_2.ctrl.T.Helper()
	varargs := []interface{}{m}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m_2.ctrl.Call(m_2, "PublishMsg", varargs...)
	ret0, _ := ret[0].(*nats.PubAck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishMsg indicates an expected call of PublishMsg.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) PublishMsg(m interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{m}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMsg", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).PublishMsg), varargs...)
}

// PublishMsgAsync mocks base method.
func (m_2 *MockNatsJetStreamContextInterface) PublishMsgAsync(m *nats.Msg, opts ...nats.PubOpt) (nats.PubAckFuture, error) {
	m_2.ctrl.T.Helper()
	varargs := []interface{}{m}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m_2.ctrl.Call(m_2, "PublishMsgAsync", varargs...)
	ret0, _ := ret[0].(nats.PubAckFuture)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishMsgAsync indicates an expected call of PublishMsgAsync.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) PublishMsgAsync(m interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{m}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMsgAsync", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).PublishMsgAsync), varargs...)
}

// PullSubscribe mocks base method.
func (m *MockNatsJetStreamContextInterface) PullSubscribe(subj, durable string, opts ...nats.SubOpt) (*nats.Subscription, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{subj, durable}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PullSubscribe", varargs...)
	ret0, _ := ret[0].(*nats.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PullSubscribe indicates an expected call of PullSubscribe.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) PullSubscribe(subj, durable interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{subj, durable}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullSubscribe", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).PullSubscribe), varargs...)
}

// PurgeStream mocks base method.
func (m *MockNatsJetStreamContextInterface) PurgeStream(name string, opts ...nats.JSOpt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{name}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PurgeStream", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// PurgeStream indicates an expected call of PurgeStream.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) PurgeStream(name interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{name}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeStream", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).PurgeStream), varargs...)
}

// QueueSubscribe mocks base method.
func (m *MockNatsJetStreamContextInterface) QueueSubscribe(subj, queue string, cb nats.MsgHandler, opts ...nats.SubOpt) (*nats.Subscription, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{subj, queue, cb}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueueSubscribe", varargs...)
	ret0, _ := ret[0].(*nats.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueueSubscribe indicates an expected call of QueueSubscribe.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) QueueSubscribe(subj, queue, cb interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{subj, queue, cb}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueSubscribe", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).QueueSubscribe), varargs...)
}

// QueueSubscribeSync mocks base method.
func (m *MockNatsJetStreamContextInterface) QueueSubscribeSync(subj, queue string, opts ...nats.SubOpt) (*nats.Subscription, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{subj, queue}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueueSubscribeSync", varargs...)
	ret0, _ := ret[0].(*nats.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueueSubscribeSync indicates an expected call of QueueSubscribeSync.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) QueueSubscribeSync(subj, queue interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{subj, queue}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueSubscribeSync", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).QueueSubscribeSync), varargs...)
}

// SecureDeleteMsg mocks base method.
func (m *MockNatsJetStreamContextInterface) SecureDeleteMsg(name string, seq uint64, opts ...nats.JSOpt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{name, seq}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SecureDeleteMsg", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SecureDeleteMsg indicates an expected call of SecureDeleteMsg.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) SecureDeleteMsg(name, seq interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{name, seq}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SecureDeleteMsg", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).SecureDeleteMsg), varargs...)
}

// StreamInfo mocks base method.
func (m *MockNatsJetStreamContextInterface) StreamInfo(stream string, opts ...nats.JSOpt) (*nats.StreamInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{stream}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamInfo", varargs...)
	ret0, _ := ret[0].(*nats.StreamInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamInfo indicates an expected call of StreamInfo.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) StreamInfo(stream interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{stream}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamInfo", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).StreamInfo), varargs...)
}

// StreamNameBySubject mocks base method.
func (m *MockNatsJetStreamContextInterface) StreamNameBySubject(arg0 string, arg1 ...nats.JSOpt) (string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamNameBySubject", varargs...)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StreamNameBySubject indicates an expected call of StreamNameBySubject.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) StreamNameBySubject(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamNameBySubject", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).StreamNameBySubject), varargs...)
}

// StreamNames mocks base method.
func (m *MockNatsJetStreamContextInterface) StreamNames(opts ...nats.JSOpt) <-chan string {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamNames", varargs...)
	ret0, _ := ret[0].(<-chan string)
	return ret0
}

// StreamNames indicates an expected call of StreamNames.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) StreamNames(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamNames", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).StreamNames), opts...)
}

// Streams mocks base method.
func (m *MockNatsJetStreamContextInterface) Streams(opts ...nats.JSOpt) <-chan *nats.StreamInfo {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Streams", varargs...)
	ret0, _ := ret[0].(<-chan *nats.StreamInfo)
	return ret0
}

// Streams indicates an expected call of Streams.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) Streams(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Streams", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).Streams), opts...)
}

// StreamsInfo mocks base method.
func (m *MockNatsJetStreamContextInterface) StreamsInfo(opts ...nats.JSOpt) <-chan *nats.StreamInfo {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StreamsInfo", varargs...)
	ret0, _ := ret[0].(<-chan *nats.StreamInfo)
	return ret0
}

// StreamsInfo indicates an expected call of StreamsInfo.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) StreamsInfo(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StreamsInfo", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).StreamsInfo), opts...)
}

// Subscribe mocks base method.
func (m *MockNatsJetStreamContextInterface) Subscribe(subj string, cb nats.MsgHandler, opts ...nats.SubOpt) (*nats.Subscription, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{subj, cb}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Subscribe", varargs...)
	ret0, _ := ret[0].(*nats.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) Subscribe(subj, cb interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{subj, cb}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).Subscribe), varargs...)
}

// SubscribeSync mocks base method.
func (m *MockNatsJetStreamContextInterface) SubscribeSync(subj string, opts ...nats.SubOpt) (*nats.Subscription, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{subj}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SubscribeSync", varargs...)
	ret0, _ := ret[0].(*nats.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SubscribeSync indicates an expected call of SubscribeSync.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) SubscribeSync(subj interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{subj}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubscribeSync", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).SubscribeSync), varargs...)
}

// UpdateConsumer mocks base method.
func (m *MockNatsJetStreamContextInterface) UpdateConsumer(stream string, cfg *nats.ConsumerConfig, opts ...nats.JSOpt) (*nats.ConsumerInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{stream, cfg}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateConsumer", varargs...)
	ret0, _ := ret[0].(*nats.ConsumerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConsumer indicates an expected call of UpdateConsumer.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) UpdateConsumer(stream, cfg interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{stream, cfg}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConsumer", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).UpdateConsumer), varargs...)
}

// UpdateStream mocks base method.
func (m *MockNatsJetStreamContextInterface) UpdateStream(cfg *nats.StreamConfig, opts ...nats.JSOpt) (*nats.StreamInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{cfg}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateStream", varargs...)
	ret0, _ := ret[0].(*nats.StreamInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStream indicates an expected call of UpdateStream.
func (mr *MockNatsJetStreamContextInterfaceMockRecorder) UpdateStream(cfg interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{cfg}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStream", reflect.TypeOf((*MockNatsJetStreamContextInterface)(nil).UpdateStream), varargs...)
}

// MockNatsKeyValueInterface is a mock of NatsKeyValueInterface interface.
type MockNatsKeyValueInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNatsKeyValueInterfaceMockRecorder
}

// MockNatsKeyValueInterfaceMockRecorder is the mock recorder for MockNatsKeyValueInterface.
type MockNatsKeyValueInterfaceMockRecorder struct {
	mock *MockNatsKeyValueInterface
}

// NewMockNatsKeyValueInterface creates a new mock instance.
func NewMockNatsKeyValueInterface(ctrl *gomock.Controller) *MockNatsKeyValueInterface {
	mock := &MockNatsKeyValueInterface{ctrl: ctrl}
	mock.recorder = &MockNatsKeyValueInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNatsKeyValueInterface) EXPECT() *MockNatsKeyValueInterfaceMockRecorder {
	return m.recorder
}

// Bucket mocks base method.
func (m *MockNatsKeyValueInterface) Bucket() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bucket")
	ret0, _ := ret[0].(string)
	return ret0
}

// Bucket indicates an expected call of Bucket.
func (mr *MockNatsKeyValueInterfaceMockRecorder) Bucket() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bucket", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).Bucket))
}

// Create mocks base method.
func (m *MockNatsKeyValueInterface) Create(key string, value []byte) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", key, value)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNatsKeyValueInterfaceMockRecorder) Create(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).Create), key, value)
}

// Delete mocks base method.
func (m *MockNatsKeyValueInterface) Delete(key string, opts ...nats.DeleteOpt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockNatsKeyValueInterfaceMockRecorder) Delete(key interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockNatsKeyValueInterface) Get(key string) (nats.KeyValueEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(nats.KeyValueEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNatsKeyValueInterfaceMockRecorder) Get(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).Get), key)
}

// GetRevision mocks base method.
func (m *MockNatsKeyValueInterface) GetRevision(key string, revision uint64) (nats.KeyValueEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRevision", key, revision)
	ret0, _ := ret[0].(nats.KeyValueEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRevision indicates an expected call of GetRevision.
func (mr *MockNatsKeyValueInterfaceMockRecorder) GetRevision(key, revision interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRevision", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).GetRevision), key, revision)
}

// History mocks base method.
func (m *MockNatsKeyValueInterface) History(key string, opts ...nats.WatchOpt) ([]nats.KeyValueEntry, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "History", varargs...)
	ret0, _ := ret[0].([]nats.KeyValueEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// History indicates an expected call of History.
func (mr *MockNatsKeyValueInterfaceMockRecorder) History(key interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "History", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).History), varargs...)
}

// Keys mocks base method.
func (m *MockNatsKeyValueInterface) Keys(opts ...nats.WatchOpt) ([]string, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Keys", varargs...)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Keys indicates an expected call of Keys.
func (mr *MockNatsKeyValueInterfaceMockRecorder) Keys(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).Keys), opts...)
}

// Purge mocks base method.
func (m *MockNatsKeyValueInterface) Purge(key string, opts ...nats.DeleteOpt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Purge", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Purge indicates an expected call of Purge.
func (mr *MockNatsKeyValueInterfaceMockRecorder) Purge(key interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Purge", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).Purge), varargs...)
}

// PurgeDeletes mocks base method.
func (m *MockNatsKeyValueInterface) PurgeDeletes(opts ...nats.PurgeOpt) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PurgeDeletes", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// PurgeDeletes indicates an expected call of PurgeDeletes.
func (mr *MockNatsKeyValueInterfaceMockRecorder) PurgeDeletes(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PurgeDeletes", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).PurgeDeletes), opts...)
}

// Put mocks base method.
func (m *MockNatsKeyValueInterface) Put(key string, value []byte) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", key, value)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockNatsKeyValueInterfaceMockRecorder) Put(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).Put), key, value)
}

// PutString mocks base method.
func (m *MockNatsKeyValueInterface) PutString(key, value string) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutString", key, value)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutString indicates an expected call of PutString.
func (mr *MockNatsKeyValueInterfaceMockRecorder) PutString(key, value interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutString", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).PutString), key, value)
}

// Status mocks base method.
func (m *MockNatsKeyValueInterface) Status() (nats.KeyValueStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(nats.KeyValueStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockNatsKeyValueInterfaceMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).Status))
}

// Update mocks base method.
func (m *MockNatsKeyValueInterface) Update(key string, value []byte, last uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", key, value, last)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNatsKeyValueInterfaceMockRecorder) Update(key, value, last interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).Update), key, value, last)
}

// Watch mocks base method.
func (m *MockNatsKeyValueInterface) Watch(keys string, opts ...nats.WatchOpt) (nats.KeyWatcher, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{keys}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Watch", varargs...)
	ret0, _ := ret[0].(nats.KeyWatcher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch.
func (mr *MockNatsKeyValueInterfaceMockRecorder) Watch(keys interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{keys}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).Watch), varargs...)
}

// WatchAll mocks base method.
func (m *MockNatsKeyValueInterface) WatchAll(opts ...nats.WatchOpt) (nats.KeyWatcher, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WatchAll", varargs...)
	ret0, _ := ret[0].(nats.KeyWatcher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchAll indicates an expected call of WatchAll.
func (mr *MockNatsKeyValueInterfaceMockRecorder) WatchAll(opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchAll", reflect.TypeOf((*MockNatsKeyValueInterface)(nil).WatchAll), opts...)
}

// MockNatsKeyValueEntryInterface is a mock of NatsKeyValueEntryInterface interface.
type MockNatsKeyValueEntryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNatsKeyValueEntryInterfaceMockRecorder
}

// MockNatsKeyValueEntryInterfaceMockRecorder is the mock recorder for MockNatsKeyValueEntryInterface.
type MockNatsKeyValueEntryInterfaceMockRecorder struct {
	mock *MockNatsKeyValueEntryInterface
}

// NewMockNatsKeyValueEntryInterface creates a new mock instance.
func NewMockNatsKeyValueEntryInterface(ctrl *gomock.Controller) *MockNatsKeyValueEntryInterface {
	mock := &MockNatsKeyValueEntryInterface{ctrl: ctrl}
	mock.recorder = &MockNatsKeyValueEntryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNatsKeyValueEntryInterface) EXPECT() *MockNatsKeyValueEntryInterfaceMockRecorder {
	return m.recorder
}

// Bucket mocks base method.
func (m *MockNatsKeyValueEntryInterface) Bucket() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bucket")
	ret0, _ := ret[0].(string)
	return ret0
}

// Bucket indicates an expected call of Bucket.
func (mr *MockNatsKeyValueEntryInterfaceMockRecorder) Bucket() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bucket", reflect.TypeOf((*MockNatsKeyValueEntryInterface)(nil).Bucket))
}

// Created mocks base method.
func (m *MockNatsKeyValueEntryInterface) Created() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Created")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Created indicates an expected call of Created.
func (mr *MockNatsKeyValueEntryInterfaceMockRecorder) Created() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Created", reflect.TypeOf((*MockNatsKeyValueEntryInterface)(nil).Created))
}

// Delta mocks base method.
func (m *MockNatsKeyValueEntryInterface) Delta() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delta")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Delta indicates an expected call of Delta.
func (mr *MockNatsKeyValueEntryInterfaceMockRecorder) Delta() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delta", reflect.TypeOf((*MockNatsKeyValueEntryInterface)(nil).Delta))
}

// Key mocks base method.
func (m *MockNatsKeyValueEntryInterface) Key() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Key")
	ret0, _ := ret[0].(string)
	return ret0
}

// Key indicates an expected call of Key.
func (mr *MockNatsKeyValueEntryInterfaceMockRecorder) Key() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Key", reflect.TypeOf((*MockNatsKeyValueEntryInterface)(nil).Key))
}

// Operation mocks base method.
func (m *MockNatsKeyValueEntryInterface) Operation() nats.KeyValueOp {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Operation")
	ret0, _ := ret[0].(nats.KeyValueOp)
	return ret0
}

// Operation indicates an expected call of Operation.
func (mr *MockNatsKeyValueEntryInterfaceMockRecorder) Operation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Operation", reflect.TypeOf((*MockNatsKeyValueEntryInterface)(nil).Operation))
}

// Revision mocks base method.
func (m *MockNatsKeyValueEntryInterface) Revision() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revision")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Revision indicates an expected call of Revision.
func (mr *MockNatsKeyValueEntryInterfaceMockRecorder) Revision() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revision", reflect.TypeOf((*MockNatsKeyValueEntryInterface)(nil).Revision))
}

// Value mocks base method.
func (m *MockNatsKeyValueEntryInterface) Value() []byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Value")
	ret0, _ := ret[0].([]byte)
	return ret0
}

// Value indicates an expected call of Value.
func (mr *MockNatsKeyValueEntryInterfaceMockRecorder) Value() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Value", reflect.TypeOf((*MockNatsKeyValueEntryInterface)(nil).Value))
}
